steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/PROJECT_ID/IMAGE', '.']
  args: ['build', '-t', 'gcr.io/registry-dev-c01c4/directus-admin-img', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  #args: ['push', 'gcr.io/PROJECT_ID/IMAGE']
  args: ['push', 'gcr.io/registry-dev-c01c4/api-server-img']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  #args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/PROJECT_ID/IMAGE', '--region', 'REGION']
  args: ['run', 'deploy', 'directus-admin-service', '--image', 'gcr.io/registry-dev-c01c4/directus-admin-img', '--region', 'us-central1']
images:
#- gcr.io/PROJECT_ID/IMAGE
- gcr.io/registry-dev-c01c4/directus-admin-img